apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-practice
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
      maxSurge: 1
  selector:
    matchLabels:
      app: qna-practice
  template:
    metadata:
      labels:
        app: qna-practice
    spec:
      containers:
      - name: qna-practice-cont
        image: prasadmahure/qna_practice:14
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerhub-secret