apiVersion: v1
kind: PersistentVolume
metadata:
  name: qna-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/qna-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qna-pvc
  namespace: qna-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi